### ISSUE TITLE
Automatic locking does not work if not logged in

### ISSUE THREAD

**Issue by lspitzner** [muennich/physlock#34]
If one accidentally switches to a vt that is not logged in, some kind of automatic locking (.e.g. on sleep/hibernate) will not work due to the utmp mechanism. Observable by doing `sleep 3; physlock` + ctrl-alt-f2 (or whatever).

This is of course a minor nitpick; i mainly wished the -u option had not been removed (and utmp does not work for some reason that i am not willing to investigate; i simply forked the project and added a root-only flag, which seems the cleanest solution for my usage).

Thanks for writing/maintaining this, nontheless.

**Comment by muennich** [comment]
Sorry but I have to label this WONTFIX. I didn't like the `-u` user selection. A possible solution for your problem is not to fail in case that the user detection via utmp fails and to only allow the root user to unlock the computer. I'm not sure about it, though. The selection of users was physlocks biggest problem right from the start and still remains so.
