### ISSUE TITLE
suspend blocked when physlock is active

### ISSUE THREAD

**Issue by craftyguy** [muennich/physlock#40]
Per the manpage:

> It is written because vlock blocks some linux kernel mechanisms like hibernate and suspend and can therefore only be used with some limitations.

However, this seems to be the case on physlock 0.5, suspend does not happen when physlock is active. This is evident because when I do log in (after a sufficient period of time in which the system _should_ have suspended), the system immediately suspends.

**Comment by muennich** [comment]
What system are you running? How are physlock and suspend activated?

**Comment by craftyguy** [comment]
Arch Linux, 4.8-rc5 kernel (but has been happening for several kernel revs)

Suspend is being activated by xfce4-power-manager after a set amount of time. Physlock is activated by xautolock, but also activated when suspending (via systemd suspend hook) so the screen is locked when resuming

**Comment by muennich** [comment]
Can you please paste the systemd service unit for physlock?

**Comment by craftyguy** [comment]
Here's the unit file that locks the screen when suspend is called:


```
[Unit]
Description=Starts physlock at suspend time
Before=sleep.target

[Service]
User=%I
Type=forking
Environment=DISPLAY=:0
ExecStart=/usr/sbin/physlock -m -s -d

[Install]
WantedBy=sleep.target
```


Just to be clear, the following events take place when this issue occurs:

1) When system is idle, xautolock calls physlock after 15 minutes, locking the screen (this is expected)
2) xfce4-power-manager is set to suspend the system when idle for 30 minutes, but the system never suspends (this is *not* expected)
3) when screen is unlocked (by authenticating with physlock), the system immediately suspends. it's as if xfce4-power-manager was prevented by physlock from calling suspend and only after physlock is unlocked can it call suspend. (this is *not* expected)
4) I wake system immediately and screen is locked by physlock, authenticate, and can use desktop (this is expected)

**Comment by muennich** [comment]
Can you please paste the output of `systemctl status` on your physlock service file? Does everything work as expected when you're not running xautolock but just the xfce4-power-manager?

**Comment by craftyguy** [comment]
Here is the output of systemctl status on the service I posted previously:

```
 suspend@clayton.service - Starts physlock at suspend time                                                     │·············································································································································································································
   Loaded: loaded (/etc/systemd/system/suspend@.service; enabled; vendor preset: disabled)                    │·············································································································································································································
   Active: inactive (dead)                                                                                    │·············································································································································································································
                                                                                                              │·············································································································································································································
Sep 13 13:21:40 computer systemd[1]: Starting Starts physlock at suspend time...                                │·············································································································································································································
Sep 13 13:21:40 computer systemd[1]: Started Starts physlock at suspend time.
```


I will disable xautolock and try that experiment.

**Comment by craftyguy** [comment]
So disabling xautolock from running still didn't have any effect. The system still suspended immediately after unlocking the system. The steps to reproduce were:

1) lock system by running `physlock -m -s`
2) let system go idle
3) after 20 minutes system is still up (xfce-power-manager **should** have suspended it after 15min)
4) authenticate with physlock
5) system immediately suspends after being unlocked

**Comment by muennich** [comment]
I can reproduce this:

    $ physlock -dms; systemctl suspend
    ==== AUTHENTICATING FOR org.freedesktop.login1.set-wall-message ===
    Authentication is required to set a wall message
    Authenticating as: bert
    Password: Failed to set wall message, ignoring: Connection timed out
    Failed to suspend system via logind: Connection timed out
    Failed to start suspend.target: Connection timed out
    See system logs and 'systemctl status suspend.target' for details.
    polkit-agent-helper-1: pam_authenticate failed: Authentication token manipulation error

Unfortunately, I do not have any idea how to solve this.

But, it turns out, that the quote in your bug report from physlocks description regarding linux kernel mechanisms still stands, as this seems to be related to systemd and/or logind and/or polkit.

**Comment by craftyguy** [comment]
Oh, that's a good simple way to reproduce it. I'm not really familiar with physlocks' inner-workings, but it seems like systemd is prevented from doing its thing by something that physlock sets up (or locks, or ??) when it is run... I have no clue how to go about debugging this further.

**Comment by craftyguy** [comment]
When you unlock, does the system suspend? It looks like in your case that the suspend is failing because your user doesn't have permission to suspend the system and the request times out. That would be different than what I'm experiencing

**Comment by muennich** [comment]
The system suspends after unlocking, if it's done up to a certain point in time after starting the command. Also, the pasted output is not generated at once. It seems that the involved components have individual timeouts.

I suspect, that the issue is caused by the suspend command's tty being inactive by the time it's run. To prove this, I've run `sleep 5; systemctl suspend` and switched to a different tty after hitting Return. It did behave exactly the same as the command above using physlock instead of sleep.

**Comment by craftyguy** [comment]
I may have found a workaround, though it seems to imply that the problem you are seeing is different than what I am seeing.. 

If I remove xfce4-power-manager and use xautolock to call `systemctl suspend` after X is idle for some amount of time, this seems to work even if physlock is active.

This is how I set it up, where physlock is enabled after 15 minutes of X being idle, and then suspend is called after 20 minutes of X being idle (so 5 minutes after physlock is activated). 

```
 xautolock -time 15 -secure -locker physlock -m -s
 xautolock -time 20 -secure -locker systemctl suspend
```

Based on your comment, it seems like this shouldn't work since it's calling `systemctl suspend` in a different tty (tty X is running on), like in your experiment. I'm not sure whether the fault lies with xfce4-power-manager, physlock, or systemd... Would it be possible to try this experiment on your system (using xautolock) to see if you can successfully suspend when physlock is active by having xautolock calling `systemctl suspend`?

**Comment by muennich** [comment]
I find it highly likely that this issue is caused by polkit, because I am completely unable to reproduce any of this after creating the file `/etc/polkit-1/rules.d/10-power.rules` with the following content:

    polkit.addRule(function(action, subject) {
    	if ((action.id == "org.freedesktop.login1.suspend" ||
    	     action.id == "org.freedesktop.login1.suspend-multiple-sessions" ||
    	     action.id == "org.freedesktop.login1.hibernate" ||
    	     action.id == "org.freedesktop.login1.hibernate-multiple-sessions" ||
    	     action.id == "org.freedesktop.login1.reboot" ||
    	     action.id == "org.freedesktop.login1.reboot-multiple-sessions" ||
    	     action.id == "org.freedesktop.login1.power-off" ||
    	     action.id == "org.freedesktop.login1.power-off-multiple-sessions") &&
   			(subject.isInGroup("power"))) {
    		return polkit.Result.YES;
    	}
    });

**Comment by craftyguy** [comment]
Thanks, I will give this a try and report back if it resolves this issue for me. I understand that this issue may not be related to physlock, but really appreciate the help you have given thus far!

**Comment by frangio** [comment]
I have this problem too. The polkit rules didn't seem to help, but I may have done something wrong. @muennich could you please say what users are in your `power` group?

**Comment by muennich** [comment]
My user is in the power group.

**Comment by rdig** [comment]
I'm seeing this behavior also on `Ubuntu 16.04.1`.

I'm entering screen power save mode using:

```
xset dpms <time>
```

**Comment by muennich** [comment]
So this is the end of physlock as I do not know whats causing this. The only thing we know is that the following combination of factors must be met in order to run into this issue:

1. systemd and polkit
2. graphical session (not on a /dev/tty)
3. physlock not called directly

I do not run into this issue because I do not use step 3.

I do not have the time to look into this. When no one else finds a fix or workaround, then I'm afraid I can only urge you to make a switch to some other locking tool.

**Comment by craftyguy** [comment]
Ok, I have a successful setup now. I have no idea what the issue was.. I suspect, as @muennich pointed out, it was a special combination of polkit permissions + some specific order of operations + ???. Here's my detailed setup just in case it helps others.


I run these when I log into X (I use i3, so these are launched using the appropriate syntax for running apps on start from i3wm in the config file):

```
# disable DPMS

xset -dpms

# Set monitor blanking to 900 seconds

xset s 900

# Use xss-lock to lock immediately when screen blanks

xss-lock  -- /usr/bin/physlock -m -s +restartsaver

# Use xautolock to suspend system after 20 minutes of inactivity

xautolock -time 20 -detectsleep -locker "systemctl suspend"

```

I start X when I log in from VT1 with this in ~/.zprofile (I use zsh):

```
xinitrc=${XINITRC:-$HOME/.xinitrc}
tty=$XDG_VTNR || exit 1

## Make sure we aren't already running in an Xserver, and only run on VT1
if [ -z "$DISPLAY" ] && [ -n $XDG_VTNR ] && [ "$XDG_VTNR" -eq 1 ]; then
        export DISPLAY=:$tty
        exec xinit "${@:-$xinitrc}" -- "$DISPLAY" vt"$tty" -keeptty
fi
```

My WM (i3) is started in `.xinitrc` with just a `exec i3`.

Here's what I have in `/etc/polkit-1/rules.d/10-power.rules`:

```
polkit.addRule(function(action, subject) {
        if ((action.id == "org.freedesktop.login1.suspend" ||
                action.id == "org.freedesktop.login1.suspend-multiple-sessions" ||
                action.id == "org.freedesktop.login1.hibernate" ||
                action.id == "org.freedesktop.login1.hibernate-multiple-sessions" ||
                action.id == "org.freedesktop.login1.reboot" ||
                action.id == "org.freedesktop.login1.reboot-multiple-sessions" ||
                action.id == "org.freedesktop.login1.power-off" ||
                action.id == "org.freedesktop.login1.power-off-multiple-sessions") &&
                (subject.isInGroup("power"))) {
                        return polkit.Result.YES;
                }
});
```

My user is in the `power` group. You need to relogin for this to take effect if you just added your user.


Again, not sure how relevant any of this is to resolving the issue for me, but just thought I would put it all out on the table just in case it helps someone else :)

@muennich I think physlock might be in the clear, at least for me :D

**Comment by frangio** [comment]
I think I understand this situation better now. After adding the polkit rules @muennich suggested the problem is resolved. However, the steps to reproduce the issue were wrong because they fail for some of us for a different reason.

Like @craftyguy, I too have a physlock service hooked up to run before suspend and hibernate:
```
[Unit]
Description=Lock
Before=sleep.target

[Service]
Type=forking
ExecStart=/usr/bin/physlock -d

[Install]
WantedBy=sleep.target
```

With this setup, physlock becomes a dependency of suspend. This means that it will be run before it, but also that **if for some reason physlock fails to start, suspend will fail as well**.

If I run `physlock -dms; systemctl suspend` as was suggested to reproduce the issue, the following can be seen in the systemd journal:

```
systemd[1]: Starting Lock...
physlock[13299]: physlock: /var/run/utmp: No entry for tty3 found
systemd[1]: physlock.service: Control process exited, code=exited status=1
systemd[1]: Failed to start Lock.
systemd[1]: Dependency failed for Sleep.
systemd[1]: Dependency failed for Suspend.
systemd-logind[507]: Operation 'sleep' finished.
```

This physlock error in itself can be reproduced by running physlock two consecutive times.

```
$ physlock -dms; physlock -dms
physlock: /var/run/utmp: No entry for tty3 found
```

It's clear then that suspend fails because it's trying to start a new physlock instance.

The following will, however, work: `systemctl start physlock; systemctl suspend`. This is because systemd will consider the physlock service to be active as long as the spawned process is running, and the dependency will be met.

It would be good to know if the issue @rdig was seeing was the same as this one.

So I think physlock is in the clear. I'm going to see if the systemd service file can be made to work around this situation. Meanwhile I have aliased `physlock` to `systemctl start physlock` (polkit permissions need to be [adjusted](https://wiki.archlinux.org/index.php/Polkit#Allow_management_of_individual_systemd_units_by_regular_users) for this to work without sudo), in case I ever lock manually.

There may be something to be done on physlock's side to handle the error better... Perhaps an option to not return an error code when there's a running instance? @muennich will be better suited to think about the security implications of that.

**Comment by craftyguy** [comment]
I'm going to close this issue, as the original author, based on my and @frangio's feedback, since it seems to be resolved after discovering the right sets of system configuration knobs to turn.

**Comment by pavlix** [comment]
@craftyguy I'm missing the systemd knob here that enables one to run `systemctl start physlock` as a user so that `xautolock` or others can use the systemd service instead of physlock. Otherwise, as running `physlock` isn't idempotent and it cannot be run when it is already running, you can't lock the screen yourself and then suspend.

**Comment by pavlix** [comment]
Workaround:

    ExecStartPre=/usr/bin/pkill physlock
